-- شغّل هذا أولاً في SQL Editor عشان تمسح كل شي قديم
-- بعدها شغّل 001_schema.sql

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS on_user_signup CASCADE;
DROP FUNCTION IF EXISTS handle_new_user CASCADE;
DROP FUNCTION IF EXISTS auto_ts CASCADE;
DROP FUNCTION IF EXISTS auto_updated_at CASCADE;
DROP FUNCTION IF EXISTS auto_update_timestamp CASCADE;
DROP FUNCTION IF EXISTS update_updated_at CASCADE;
DROP FUNCTION IF EXISTS update_updated_at_column CASCADE;
DROP FUNCTION IF EXISTS get_user_tenant_ids CASCADE;
DROP FUNCTION IF EXISTS is_tenant_member CASCADE;
DROP TABLE IF EXISTS fabric_transactions CASCADE;
DROP TABLE IF EXISTS fabric_stock CASCADE;
DROP TABLE IF EXISTS fabric_usage_defaults CASCADE;
DROP TABLE IF EXISTS fabrics CASCADE;
DROP TABLE IF EXISTS fabric_brands CASCADE;
DROP TABLE IF EXISTS order_status_logs CASCADE;
DROP TABLE IF EXISTS purchase_orders CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS measurements CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS usage_tracking CASCADE;
DROP TABLE IF EXISTS store_members CASCADE;
DROP TABLE IF EXISTS tenant_members CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS stores CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS plans CASCADE;
DROP TYPE IF EXISTS order_status CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
