'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { supabase } from '@/lib/supabase';
import { Scissors, CheckCircle, ArrowLeft, Smartphone, MessageCircle, Ruler, Package, Users, BarChart3, Truck } from 'lucide-react';
export default function Home() {
  const r=useRouter(); const [ok,setOk]=useState(false);
  useEffect(()=>{supabase.auth.getUser().then(({data:{user}})=>{if(user)r.replace('/dashboard');else setOk(true);});},[r]);
  if(!ok) return <div className="min-h-screen flex items-center justify-center"><div className="w-8 h-8 border-2 border-brand-500 border-t-transparent rounded-full animate-spin"/></div>;
  const feats=[{icon:Scissors,t:'إدارة الطلبات',d:'تتبع كل طلب من الاستلام حتى التسليم بـ ٧ مراحل'},{icon:Ruler,t:'المقاسات الذكية',d:'١٣ قياس + تفاصيل التصميم (ياقة، جيب، أزرار)'},{icon:MessageCircle,t:'إشعارات واتساب',d:'تحديثات تلقائية للعميل عند كل تغيير'},{icon:Package,t:'إدارة المخزون',d:'تتبع الأقمشة بالمتر مع خصم تلقائي (٣ متر/ثوب)'},{icon:Truck,t:'الموردين',d:'إدارة الموردين + أوامر شراء PDF'},{icon:Users,t:'فريق العمل + فروع',d:'أدوار مختلفة + فروع + معمل + مستودع'}];
  return <div className="min-h-screen bg-srf-50" dir="rtl">
    <nav className="flex items-center justify-between max-w-6xl mx-auto px-6 py-5"><div className="flex items-center gap-2"><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-brand-400 to-brand-600 flex items-center justify-center"><Scissors className="w-5 h-5 text-white"/></div><span className="text-xl font-bold text-srf-900">خيّاط</span></div><div className="flex items-center gap-3"><button onClick={()=>r.push('/login')} className="text-sm font-medium text-srf-600 px-4 py-2">دخول</button><button onClick={()=>r.push('/register')} className="text-sm font-medium bg-brand-500 text-white px-5 py-2.5 rounded-xl hover:bg-brand-600 press">ابدأ مجاناً</button></div></nav>
    <div className="max-w-4xl mx-auto px-6 pt-16 pb-24 text-center"><div className="inline-flex items-center gap-2 bg-brand-50 border border-brand-200 text-brand-700 text-sm font-medium px-4 py-1.5 rounded-full mb-6"><Smartphone className="w-4 h-4"/>يشتغل من أي متصفح</div><h1 className="text-4xl sm:text-5xl font-bold text-srf-900 leading-tight mb-6">أدِر محل الخياطة<br/><span className="text-brand-500">من جوالك</span></h1><p className="text-lg text-srf-500 max-w-2xl mx-auto mb-10">نظام متكامل لإدارة الطلبات والمقاسات والمخزون والموردين. ودّع الدفاتر — كل شي في مكان واحد.</p><button onClick={()=>r.push('/register')} className="bg-brand-500 text-white text-lg font-semibold px-8 py-3.5 rounded-2xl hover:bg-brand-600 shadow-lg shadow-brand-500/20 press flex items-center gap-2 mx-auto">ابدأ مجاناً <ArrowLeft className="w-5 h-5"/></button><p className="text-sm text-srf-400 mt-4">بدون بطاقة ائتمان — كل الميزات متاحة</p></div>
    <section className="max-w-6xl mx-auto px-6 py-20"><h2 className="text-3xl font-bold text-center text-srf-900 mb-14">كل اللي تحتاجه</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{feats.map((f,i)=><div key={i} className="bg-white border border-srf-200/60 rounded-2xl p-6 shadow-sm"><div className="w-12 h-12 rounded-xl bg-brand-50 flex items-center justify-center mb-4"><f.icon className="w-6 h-6 text-brand-600"/></div><h3 className="text-base font-bold text-srf-800 mb-2">{f.t}</h3><p className="text-sm text-srf-500">{f.d}</p></div>)}</div></section>
    <section className="max-w-3xl mx-auto px-6 py-20 text-center"><h2 className="text-3xl font-bold text-srf-900 mb-4">جاهز تودّع الدفاتر؟</h2><p className="text-srf-500 mb-8">سجّل الحين وابدأ — كل الميزات متاحة مجاناً</p><button onClick={()=>r.push('/register')} className="bg-brand-500 text-white text-lg font-semibold px-10 py-4 rounded-2xl hover:bg-brand-600 shadow-lg shadow-brand-500/20 press">ابدأ مجاناً</button></section>
    <footer className="border-t border-srf-200 py-8 text-center"><p className="text-xs text-srf-400">© {new Date().getFullYear()} خيّاط</p></footer>
  </div>;
}
